### ISSUE TITLE
Error while loading rule 'whitelist': context.getConfigBaseDir is not a function

### ISSUE THREAD

**Issue by TAKEDA-Takashi** [textlint/textlint-filter-rule-whitelist#4]
An error occurred when updating to v1.2.1.

Paste the stack trace.

```
linter-registry.js [sm]:137 [Linter] Error running textlint TypeError: Error while loading rule 'whitelist': context.getConfigBaseDir is not a function
    at module.exports (/Users/takashi/Documents/textlint_env/node_modules/textlint-filter-rule-whitelist/lib/textlint-filter-rule-whitelist.js:51:33)
    at TextLintCoreTask.tryToGetRuleObject (/Users/takashi/.atom/packages/linter-textlint/node_modules/textlint/lib/task/textlint-core-task.js:241:24)
    at TextLintCoreTask.tryToAddListenRule (/Users/takashi/.atom/packages/linter-textlint/node_modules/textlint/lib/task/textlint-core-task.js:261:35)
    at /Users/takashi/.atom/packages/linter-textlint/node_modules/textlint/lib/task/linter-task.js:122:24
    at /Users/takashi/.atom/packages/linter-textlint/node_modules/textlint/lib/core/rule-creator-set.js:127:24
    at Array.forEach (native)
    at RuleCreatorSet.forEach (/Users/takashi/.atom/packages/linter-textlint/node_modules/textlint/lib/core/rule-creator-set.js:126:35)
    at TextLintCoreTask._setupRules (/Users/takashi/.atom/packages/linter-textlint/node_modules/textlint/lib/task/linter-task.js:109:39)
    at new TextLintCoreTask (/Users/takashi/.atom/packages/linter-textlint/node_modules/textlint/lib/task/linter-task.js:67:15)
    at LinterProcessor.process (/Users/takashi/.atom/packages/linter-textlint/node_modules/textlint/lib/linter/linter-processor.js:71:24)
    at TextlintCore._parallelProcess (/Users/takashi/.atom/packages/linter-textlint/node_modules/textlint/lib/textlint-core.js:253:36)
    at /Users/takashi/.atom/packages/linter-textlint/node_modules/textlint/lib/textlint-core.js:310:31
    at tryCatcher (/Users/takashi/.atom/packages/linter-textlint/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/takashi/.atom/packages/linter-textlint/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/Users/takashi/.atom/packages/linter-textlint/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/Users/takashi/.atom/packages/linter-textlint/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/Users/takashi/.atom/packages/linter-textlint/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/Users/takashi/.atom/packages/linter-textlint/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/Users/takashi/.atom/packages/linter-textlint/node_modules/bluebird/js/release/async.js:143:10)
    at Async.drainQueues (/Users/takashi/.atom/packages/linter-textlint/node_modules/bluebird/js/release/async.js:17:14)
```

**Comment by azu** [comment]
@TAKEDA-Takashi I think that is textlint version issue.

Please telll me following result.

```
$ textlint --version
# or
$(npm bin)/textlint --version
# or
./node_modules/.bin/textlint --version
```

**Comment by TAKEDA-Takashi** [comment]
@azu textlint version Paste it. Thank you.

```
$ ./node_modules/.bin/textlint --version
v9.1.1
```

**Comment by azu** [comment]
@TAKEDA-Takashi Thanks for reply.

Ah, Maybe your atom plugin use following `textlint` binary.
This will be textlint ver 8.x.x.

```
/Users/takashi/.atom/packages/linter-textlint/node_modules/.bin/textlint --version
```

And, I've released hot fix version for textlint 8.x.x.

- https://github.com/textlint/textlint-filter-rule-whitelist/releases/tag/1.2.2

Please try it.

**Comment by TAKEDA-Takashi** [comment]
@azu It worked by updating to v1.2.2! Thank you!
By the way, I checked the version of textlint of atom plugin and it was 7 series.

```
$ /Users/takashi/.atom/packages/linter-textlint/node_modules/.bin/textlint --version
v7.4.0
```

**Comment by azu** [comment]
> I checked the version of textlint of atom plugin and it was 7 series.

I see. It seem to be linter-textlint issue.

I've filed this as issue https://github.com/1000ch/linter-textlint/issues/39

Thanks for report!
